id: 244
title: 'IV Curso de divulgación científica na sociedade: Transmisión e información. A importancia do deseño e a configuración da mensaxe'
body:
  -
    text: 'O [programa](http://www.udc.es/occ/gal/2011/cveran/programas2011/2011cv010.pdf) do curso que se celebra o 6 e o 7 de xullo na sala de prensa da reitoría da UDC, arranca o venres pola mañá coas conferencias do vicerreitor de Cultura e Comunicación da UDC, Luís Caparrós, e de Manuela Mariño, deseñadora na Voz de Galicia. Xa pola tarde, desenvolverase unha mesa redonda que leva por título **Transmisión da información a través do deseño** e na que participarán o presidente da DAG e profesor de Deseño na UVigo, [Marcos Dopico](http://www.dedominiopublico.com/), a deseñadora gráfica, tamén membro da DAG, [Uqui Permui](http://www.uquicebra.com/), o vicedecano da Facultade de Belas Artes da Uvigo, Fernando Suárez, e Javier Barreira, account manager de Elogia. O curso clausurarase o sábado cun obradoiro de deseño impartido por outro socio da DAG, neste caso, [Daniel Bembibre](http://www.studiobelda.com/), e que durará todo o día. Toda a información e matrícula, [aquí](http://www.udc.es/occ/gal/2011/cveran/cursos2011/2011curso10.htm).'
    type: text
  -
    list: ''
    image: /news/images/553e7a9d6e55d-mensaxe-desen-o.jpg
    text: ''
    type: image
intro: 'A Universidade da Coruña dedica esta IV edición do Curso de divulgación científica na sociedade á importancia da imaxe e do deseño na configuración das mensaxes.'
slug: iv-curso-de-divulgacion-cientifica-na-sociedade-transmision-e-informacion-a-importancia-do-deseno-e-a-configuracion-da-mensaxe
tags: []
lang: gl
draft: false
date: 2011-06-23T10:35:00+00:00
