id: 243
title: "IV Curso de divulgación científica en la sociedad: Transmisión e información. La importancia del diseño y la configuración del mensaje"
body:
  - text: "El [programa](http://www.udc.es/occ/gal/2011/cveran/programas2011/2011cv010.pdf) del curso que se celebra el 6 y el 7 de julio en la sala de prensa de la rectoría de la UDC, arranca el viernes por la mañana con las conferencias del vicerrector de Cultura y Comunicación de la UDC, Luís Caparrós, y de Manuela Mariño, diseñadora de La Voz de Galicia. Ya por la tarde, se desarrollará una mesa redonda que lleva por título **Transmisión de la información a través del diseño** y en la que participarán el presidente de la DAG y profesor de Diseño en la UVigo, [Marcos Dopico](http://www.dedominiopublico.com/), la diseñadora gráfica, también miembro de la DAG, [Uqui Permui](http://www.uquicebra.com/), el vicedecano de la Facultad de Bellas Artes de UVigo, Fernando Suárez, y Javier Barreira, account manager de Elogia. El curso se clausurará el sábado con un taller de diseño impartido por otro socio de la DAG, en este caso, [Daniel Bembibre](http://www.studiobelda.com/), y que durará todo el día. Toda la información y matrícula, [aquí](http://www.udc.es/occ/gal/2011/cveran/cursos2011/2011curso10.htm)."
    type: text
  - list: ""
    image: /img/news/images/553e7a9d6b45b-mensaxe-desen-o.jpg
    text: ""
    type: image
intro: "La Universidad de la Coruña dedica esta IV edición del Curso de divulgación científica en la sociedad a la importancia de la imagen y del diseño en la configuración de los mensajes."
slug: iv-curso-de-divulgacion-cientifica-en-la-sociedad-transmision-e-informacion-la-importancia-del-diseno-y-la-configuracion-del-mensaje
tags: []
lang: es
draft: false
date: 2011-06-23T10:35:00+00:00
