id: 296
title: 'Productos Koala–Grupo ECI'
slug: productos-koala
body:
  -
    text: 'Ilustraciones vectoriales para _packaging_.'
    type: text
  -
    image: /portfolios/images/01.jpg
    text: ''
    type: image
  -
    image: /portfolios/images/02.jpg
    text: ''
    type: image
  -
    image: /portfolios/images/03.jpg
    text: ''
    type: image
  -
    image: /portfolios/images/04.jpg
    text: ''
    type: image
  -
    image: /portfolios/images/05.jpg
    text: ''
    type: image
  -
    image: /portfolios/images/ilustracions.jpg
    text: ''
    type: image
cover: /portfolios/covers//03.jpg
tags: []
members_id:
  - 69
lang: es
info:
  -
    - Cliente
    - 'Productos Koala–Grupo ECI (El Corte Inglés e Hipercor)'
draft: false
