id: 296
title: 'Productos Koala–Grupo ECI'
slug: productos-koala
body:
  -
    text: 'Ilustraciones vectoriales para _packaging_.'
    type: text
  -
    image: /img/portfolio/images/01.jpg
    text: ''
    type: image
  -
    image: /img/portfolio/images/02.jpg
    text: ''
    type: image
  -
    image: /img/portfolio/images/03.jpg
    text: ''
    type: image
  -
    image: /img/portfolio/images/04.jpg
    text: ''
    type: image
  -
    image: /img/portfolio/images/05.jpg
    text: ''
    type: image
  -
    image: /img/portfolio/images/ilustracions.jpg
    text: ''
    type: image
cover: /img/portfolio/covers/03.jpg
tags: []
members_id:
  - 69
lang: es
info:
  -
    name: Cliente
    value: 'Productos Koala–Grupo ECI (El Corte Inglés e Hipercor)'
draft: false
